# k3s-gitops/infrastructure/zot/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-registry.yaml
  - configmap-config.yaml
  - sealedsecret-htpasswd.yaml
