---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: zot-secret
  namespace: zot
spec:
  encryptedData:
    htpasswd: AgCpgPecp1u3VvZ+VYrDNUjC3TIVR/vC2YhZRTFGLL/O+QA9G2sqjtA8ciauCr/42SkUcK8dL2mP8g4y68is/LTQjAdnEQdC85+y18pLRfKHYfiDIO09ZxzFvABt9nGDBoi6z27Cg4N0EAi7l7m2BhV3LaMen/e2TzEnFKL+UoFHz0nSsNAMLDUrSIrrF2231/GhnVxfEMEX/fZ9Ram6UZYbfUUUl8O4jeus+zzbBgBUGrxSZrsZ8hEgNDZXsukKFmLViuzfGfRQQ3+kDQxclOCIq/6bKFc4wj/FYGxa3QD55K0KTtrc3DlKcSBzsuPOLN4EAYMP0k0STtfKXKPbjBJUiz2YCyZe+YXREoUaYlqy2+6VKaj7AWK5heUifZC6XAuCRuLVP1/bxfeZBUbnRpmi+iOFe/Jm8ZDBjXZ1NRkW+D/uVTEiZ2aCk4PT5FXCOaVl2l7INOzbaIIp1FZvTSBAY0M9GwQiN4J7N1IkCO4WOizaFvFAX81a7CBHD7nkTwFDCoX7pQCZ9b20w0d7hPN0wT4plGCcArnePOR5rgmRS5uSAG0XZMDme6MMGqOoJfK+27SbURAHs5rJZdDviHIIZzhA5DP0GjsDY5UnGcfqgm3bEhsg71pP7STXcsm5tCEVsbemzr8brbuW9BHe2AtqCHiuUMxXGwBckO2ZVZ11QXkDLo8LpFnU1bCyoA48onLqKWZqPFrCZ4Y+dQQGScbHP4cAFwUxA/yn4I6N3UTGqHXhkkAVgJkmoM/zQ0c0BUkfiYYKZqA0s6DVHAXyYUxDKNqTBw==
  template:
    metadata:
      name: zot-secret
      namespace: zot
