---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cnpg-barman-b2-credentials
  namespace: cnpg-system
spec:
  encryptedData:
    ACCESS_KEY_ID: AgAuUGewXDZDS6TGJ/bYYMlXdGDsE4lqi+S5ZHDEckx3CGuCyMZZyCqoKqkhPGefEuo3Vephlom0hlnrwjTgYsrtS4Dx5CAGQ0yZB6Jc8tPER/g9BSnPIiUvkAdNvy5u3XJSIf2B77sXtkLiXmSRhzvT7vyNKN4x89T771GDtksUTeKatG7ghZ7fXgkcWCNpxiWgA5NVNawGA0Mm2xWpEejdoCtsviAMyHkneDGSdQnysoic7lGl0l89TGJktXuoeTaw8UNzELCyxauLMJaXtPyu19DllyIx9M4GclVLMuQT1U3STwiQERQ84TxLqZno2k2ZoazWJ7tkhFuADtWbzRY8ZOqbARgEjNndU5/vi9zMetNJ9Fc8Qfu2yDKM69u6vhbWpl7zgRhw09vR7idwzXhvGW9uE0o3hhFuT/E66z6LXiTVOLpE+64vzALBKcjMWnqDUp/KSKSdARCHC6DTRzFKkNqGZcfC9ae02wyhLKWMRB/0cd8XFlUFuCDyRqMtXx7AOqluvNiq+v/k/UU1qC1triah6HS/sPYueUxBy/Qb4r+TK31DyX4OVxfssmQTVmioEyNW3gpjyFAYYvtdpmK1zPsHrgNyYy9ll/GI7mOWMpdXV1nX2D21QkXqHPx1hNEdASAQ6ITdgqHAGxHu4S1H3GLK23dbtXjeiMmlGzgMj7KOWjCR+d7sh1T8MUWSSUMd9lT5qQ1Tt6jU9jbHs3xyOwErfHPDr4GQ
    ACCESS_SECRET_KEY: AgCsuuTqeXskOLT2DUP3wYUkv8tywltX+VK5JKDW2FshKhd9MfregLQYY7xVCnkArYR8nABAtpC9+IF6yKNkoCRQZz2ZNB6y/ZDi9Tvp50QSRZ6KpvbQYte9/U1++O4E7OVw/HIjIbBgO2IVjtXRaou6s3T0eihnQtb39cZdNSvwx056PM7dIcSG0jrCBmlSckxzD0B3xEUZ4wlfkKuZ8JFYOe8szbgHaeHSQkzRxcxt2XrDtEpK2Ocs+Et+e0GfXUJmew9/SlxZl00NYvcqckZYR5QT/ctbGO08CK0QN+mt+a2ltg3zPWhjRH6lYRdkudoeYgTjapnW9vsqT3ro3nz1gVd6lCdXblEXBttidUqHJgMGAn6vrH+QubvpRB6xJLX1Ve6Hjpeq2aHCOYvNIKvqLdBGO3vv8yxWUAcUlYUNosSysaKK2J34qg0NAv8m+e5Z3hm5sVshvROCgeUHjsiHkk+8fCubPIxQZnYL25delGErBrbtcqD3CMhqJU7xKH4phIegjC7FKWxoZ8xNQg78vg1EnGzPX3ih8rcCHwAGj0lxbm/DAkai1iEShc8fwJ0qga3yTYfoixFu8LSVC6NDygS3pf1x65tMTlAyoLOtxhuZU+sAVp6UO9OfMNXxiyt8c4kwfCaCvIwzVobRxJw7AOzPt4KYv1yPN6rMwFb7nwLE8HZoMIVaYlfY7pJOKIJ2haWxVDTl+0nJXcy54wdrckyLqMHlU7d6uyea1LPa
  template:
    metadata:
      name: cnpg-barman-b2-credentials
      namespace: cnpg-system
      #annotations: # This should only be uncommented once I have other namespaces I need to provide this secret to. Like Paperless.
      #  reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      #  reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "adguard,jellyfin,monitoring,authentik"
      #  reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      #  reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "adguard,jellyfin,monitoring,authentik"