# k3s-gitops/ansible/inventory/group_vars/all.yaml
ansible_user: ubuntu
ansible_ssh_private_key_file: ~/.ssh/id_ed25519
ansible_python_interpreter: /usr/bin/python3

k3s_version: v1.29.0+k3s1
k3s_cluster_cidr: "10.42.0.0/16"
k3s_service_cidr: "10.43.0.0/16"
k3s_cluster_dns: "10.43.0.10"
k3s_master_ip: "192.168.7.15"

argocd_namespace: argocd
gitops_repo: "https://github.com/RockBrackenshield/k3s-gitops"
domain: hermnet.org
