# k3s-gitops/infrastructure/metallb/ip-pool.yaml
# ---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: infrastructure-pool
  namespace: metallb-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  addresses:
    - 192.168.7.200-192.168.7.220
  autoAssign: false
  avoidBuggyIPs: true
