# k3s-gitops/infrastructure/adguard/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - blueprints
  - backup
  - postgresql
  - server
  - worker
  - ingressroute.yaml
  - middleware.yaml
  - namespace.yaml
  - sealed-authentik-secret.yaml