apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-jellyfin
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "Prune=false"
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: longhorn
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: media
    volumeAttributes:
      numberOfReplicas: "1"
      staleReplicaTimeout: "2880"
  claimRef:
    namespace: jellyfin
    name: media