#---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: paperless-samba-creds
  namespace: paperless
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  encryptedData:
    password: AgCKb6cjL4ZSVtahMuAbJdik1P6i0s++k0U20gh9ymITbW+OaoYoLwPrRD2RXcRl5WTEqeA+n1RRXZLxLyD0Xnh3oOz0dTucBKjGNAwo9+CxCnuwi4IO0tsdey41MZJHtxAh9rn84ogU4AKuqnRv+PhKERvs3NQKpBwQJcrnBf999BUgXy2LT9xCQq1yepU4orOXOqesZ3PSKgDnXbfm5/9vhatfo7h/l9sSS8WjWQqX/paNL3DS888MmXeA7YysIMKxqt+flOQzVQfavkPzHzYYVIbn21DARgLClnr/llnEpdycrzMvaaoXtxSPR0K5fr5RwPdZpom8vVFGsIosskL0K0eBaJ6QyKC5uF8CMUCJjWCxPMZexbf7Xv3DG3rzTP9yaavS+P52rXXm3bGndyYR41RRJzL6jnkM2WM2uf1grILpgnAfzuZ8JqUQdcoF/J9RddxcE+Qk1AC5ptNNMgJ3cgrv+UgxjUrdiP5H2z5uirM4nNs+az6OC4KppTxskXQ/p6de9jOUMmE9ScQ4iRMobbgaUa0HQEecePbo1nKV0JkAOcW4twH9V9amjr5AAOFYPPmu4CozmiR33bx9L1M3lkygKxtgnD5UdKKBuhOD0IuyADA2edd8XImOdeqqiNjJYKGRpJ3LDFGgoqcLbUKkamR127HSS413TUCrFhbyT0NrjLn+38QsFugF5vZNU507MPFJJqyV2ivunpA=
    username: AgCQvbvxXF+h4pUDJkoQFkyC6Svlcw13RdGleZOyG8GvUGw84FmxyliSzue8RsP9r2znAP61yKpp0w4AuyByZKbEhY+zYSMPMQJgRq2s216Rsm+xAtKwRDyzWEyVQ9/EItlnL8vRAQS9GlbvNfjkHICrQdoyp5gLgIvdzorQsEa6D3ovSP61eGkr2xFF1wRuH4HXZlJCoFjAbUPhAdJXbYcgjXfkkBM4hp8kXDEsqWf2iuNYG5aTSF0WLwhHvPErW6K4vpDkRuZGH6lbooEeq0bV+BBmscRlmtTcY4ySTpPOELpzTwrQUbGz7T1J/k7kEL3e2e+M2PGx3dMmCGu3H5kma6jLSUKPKhhflazkYFUUm6S4OTr7XZsdqFY8PvIA9DzYvEZxj8NSDyBrTWw5Pndstb+v24kGjC+uhSbrHQbAeONs8hEKqQ6QimCutq1NEJYHcVtAR+CB2bhf+eLxoJ7ZjkMLb39fUqwb0roEGIPKVg2zLYiEMtFLRBsWDDJsxX/8QPdrh74lrVB+CsbTa312dEIzbvvqeEtf17b9t2DLX9jBbS55p9Qaq1eBhc+b3WbBdT/zohoq5alnEK7gLtTcJ6O8kxhyjR7VcS/9xK1bSHRNZLVu5nchRHWrQ3gweyTFgnTypPxvVeLzD3v4gEEi9bi0+K1xKN4aK4JoTNGkYdsNbAQvFvfBvrRY145zp4OLGXc=
  template:
    metadata:
      name: paperless-samba-creds
      namespace: paperless
    type: Opaque
