# infrastructure/authentik/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authentik-server
  namespace: authentik
  labels:
    app.kubernetes.io/name: authentik-server
    app.kubernetes.io/part-of: authentik
spec:
  selector:
    app.kubernetes.io/name: authentik-server
    app.kubernetes.io/part-of: authentik
  ports:
    - name: http
      port: 9000
      targetPort: http
    - name: https
      port: 9443
      targetPort: https