# apps/sftpgo/resources/ingressroute.yaml
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: sftpgo
  namespace: sftpgo
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`sftp.hermnet.org`) && PathPrefix(`/dav`)
      kind: Rule
      priority: 10
      services:
        - name: sftpgo
          port: 81
    - match: Host(`sftp.hermnet.org`)
      kind: Rule
      priority: 1
      services:
        - name: sftpgo
          port: 80
      middlewares:
        - name: authentik-forwardauth   # confirm your actual Middleware name/namespace
          namespace: authentik
  tls:
    secretName: hermnet-org-tls          # confirm your actual wildcard cert Secret name