# apps/sftpgo/resources/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingressroute.yaml
  - sealed-sftpgo-admin-secret.yaml
  - pvc-jellyfin-media.yaml