# apps/sftpgo/resources/pv-jellyfin-media-shared.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sftpgo-media
  namespace: sftpgo
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 500Gi
  volumeName: sftpgo-media