# apps/sftpgo/resources/sealed-sftpgo-admin-secret.yaml.example
#
# Seal each key with:
#   printf '%s' 'admin' > /tmp/u && printf '%s' "$(openssl rand -base64 24)" > /tmp/p
#   kubeseal --raw --scope namespace-wide --namespace sftpgo --name sftpgo-admin-credentials --from-file=/tmp/u
#   kubeseal --raw --scope namespace-wide --namespace sftpgo --name sftpgo-admin-credentials --from-file=/tmp/p
#   rm /tmp/u /tmp/p
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sftpgo-admin-credentials
  namespace: sftpgo
spec:
  encryptedData:
    SFTPGO_DEFAULT_ADMIN_USERNAME: AgBlSR5+n3rXrveSRVlV0Tu25z+ikS93HoTe0e2JLPSSK2dVZ1bCyAPivVQ/Zb9NPq+urGdylMrm8jZVeYKope5azou0q2WMNWEDsDBRNBIIlPQcfxHLV6Nx5YMr7KiiLKg1CWRbxt/x4ofn2EGf+ohcd1S3TkBVRaadMSjFeR+ae84Iuhxbxij/2g78FJfgo4aKev/1oDc9yqmQH+MWoaDlQvy6Oe12sL5RYvPxMfDhlo9Z/s6CcpU3+SaYBFqJCGRSa1fsD1L4rRPvNI37HxBt1PZV2/Ec1Hh/HcmJ1R8elc+uFztiAp6oB4mkFKbwmkm40eM6fYK2KikgdxzZhpPRw8U+lICLTUfcjgJyn0g8xkSWlpICGKBRruv4JFJ/+MkoRLEKpOcfMCv8SSv5+8nrtNp5x4zA1QCdJ+LFjMonmtvggd3QK3JTRxtnBnvTTyUF6eseEIuSvN53fdTNkuLYq7OlasUpUUAbsqdnJnPfPfshsMFOE5Gi97yqZgV7TstVg5Vky4w7eeeutCTcEhsM/JxjDSIgWaIEWAc+YLeWpt2iNIDx8YIQLX+ZMJmJ4W+QdcDuqf3hEofq67LXmXcsW27uGtNRl47CnaZDu9+57WiPt6k1zom/ZBUQGVgb/5BENSek99EkbfiqsVOhxAk29qrVBlWv/qOGhSc7k2kRWAL5us9gmFZ4chRQSxCvvzkSzO6OWQ==
    SFTPGO_DEFAULT_ADMIN_PASSWORD: AgBPAhGAWJes/L5DQLuc9M+BwsPOC7mdmEdk56ApcnGX5PWBzK0d/Mw14H47nQn/9S3jsEZx4sXPWvT2KpP5pbZlqsiSY7GOR2JWkprFlADGNhAQmfeHpeZ9g0AiLn0ODLHlrNZ1A3cwtLMXRsgs8SbnMOP+wLZvHtI6nPXyeFF+SixovzL8L3EuA6px7otIS8sSx0DZDdXdloqkboFEm9YbRvtuRsXGJ/pYrR86DX1E84fkyEkwZF5CmS+2Rb/LqkrW/Cb9WGmWsM49F6qtYafwKihl/m18ixodXxFjDom0j4VQsQ63EcSbGTiH/ceN2tNRBrXJ+0JSJq0Dcqj7xnTJZBEokVxVZgVPc+ubtH798PMbh7D73n0XTa6dQ6rd75kGUBeCGHpszSAV8BGt2HfuifZP9U6CJMaFwHMyfh4wQbBI6u56DagbCPxSbTw7VuEl7DFfy2KtpU6zLoO6+/cUtLsViNBIV05cQPa35t5TZxJsBHh1GAdf+L5hvo1JH99W0pmmwIeaBtQnEilDzv0dpu2PiG83/6v63fWcpzSvGclMi0LSDAiPLKfePBq5WqS8tql3MQPoR3ViiA6t4StJ3PZY696ASMLnUF2ek7JDv7kkAz1OLulh8KKgiq9uqg/DMWxr12/FZOmG4AGw7eI1q3+21xa3M1BZ981iADb21a/i/NOCCSJFnvYULyaQazBd/66Zgpb0KUaa9eQwOGv0VD2wvES0/FWBKyYTqktgkB593AedJ0WYLCxgjkI=
  template:
    metadata:
      name: sftpgo-admin-credentials
      namespace: sftpgo
    type: Opaque