# apps/sftpgo/resources/sealed-sftpgo-admin-secret.yaml.example
#
# Seal each key with:
#   printf '%s' 'admin' > /tmp/u && printf '%s' "$(openssl rand -base64 24)" > /tmp/p
#   kubeseal --raw --scope namespace-wide --namespace sftpgo --name sftpgo-admin-credentials --from-file=/tmp/u
#   kubeseal --raw --scope namespace-wide --namespace sftpgo --name sftpgo-admin-credentials --from-file=/tmp/p
#   rm /tmp/u /tmp/p
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sftpgo-admin-credentials
  namespace: sftpgo
spec:
  encryptedData:
    SFTPGO_DEFAULT_ADMIN_USERNAME: AgCdV1mydRo6iSLySB1Ts7lfiAHP87RNSwgedglcfkxeTlxSGUBn4oGz3+P9oVjR363r0BQoZn0OAZ0oIBgyteN39Vkb1BbcK2pe3C1Ezch0xWM1focLiMvM+zZIaaduaRwmEDKehqa7/g9RNyaY8L4tdCkhnGvHUuEij5PA1faff3j9dymgs4ySc6yULfaAvrDZBD0K/daxrbSYCQhuXaMe76D9ZYVzS2I1P1HQiN74BO2qmOsvriuHNcWm9pOI8nOBTLPUobKM5tOQQ2oBt0fYQSbilhHOM4MOiSEwrHh6ZyiUvhid02whqBVrRBGl1xro8cc7cfARKhFEVJfqBzzt8I+7YeCoMkgf+pQDwtHijb5cmZGstfW5UWf7qwg0FxnLd5utRxBj+O4pwL/1PUjEQr/dUtzPIo/zsTtdkusYYkrab124ZTG40jws3bC7kejYNeF0wMnXhq2Q42+w+SjEmZgRfD7Zn2YTRqaOS/4l0jxyUp8Ox3UrJhFyPXiR1zC8rrIaBFGS7moJRBX9iZQMboMYnL7HDjoXjxm+DTcyx6nUvboQQOd3NqbK2Kkx1zLQdngo696+TDYx6jdblzu82y2jyhiDDax2naV8wGfnjtvrtYwwdtzOQmJCvT1i6sy4BciYRJ+OxsiCePgRU+GSBP53JF34fsoFNJZFBbrL6fihUX5eae/7CNiVk+tGEszik6vrULf+6Oc58WJ4IITSWaqo365YiOBBW37EK4fPXcs=
    SFTPGO_DEFAULT_ADMIN_PASSWORD: AgB7flirqrq8n4lQtt/j+eSgyRjqsJvb8Ln1XtFPmqKHZLKyw1eS4a3xMkV2UI8S1PoQTFQKqTKF81wgkWFCTglL6Hkkc7LS3vBEA+oEH0j1HygwZy0BjSRoi8tqZ+s15ZxLHgiz3tkx8LOK66bPanEpB3XCNEhgcvscwiul4wRIKZsdTJWlnXwN4GjI4qleEJPXwi6k4HviYC+kMXSNQr5LRJkOwEZCH0IFGIDaSzJ28D/O9oPwPR+sk0Yn+IStxseny3gxxjW0slKfBNp9pFEvsDMXvQOG/WV0Y6EBx6QBZJoeP8q2b7dcmySQyQkgc/VQTwYvKYiLa4tp2/rbZKQWlNYMGZFO0fw7KRRNLSU3HEAUYSwOfY/fRoguMz9RhYNibs+8oxuxxiL3/gyo0ywgxWEsNChH2+n+ko35SP7x+8ImUR606Eta05tKdrp3t5ADDnh9sz6c9dgznVwjpRrPi2hcXzFVnuWTezvH98POnj+uHcHcoYTVB99HhsZt9ktvGua62vtCUIQtood2H3JYmtKyYSCw3qEyduxFrfIA5Q1xt9WHt4iu6vXv+fHh5zU7ultsknXC7ZJMTn9ZygxgwQtwRIVUnutLmKwAJa9PTpv9P0Cb/vEKGKfiin9wLi/H1oaYpwK2PoImVQJJ7ly8I/KfLfyaB4aj4oIcAEvmP8dGIuHLF7+JUTXQONuU7CJjkO5d3A==
  template:
    metadata:
      name: sftpgo-admin-credentials
      namespace: sftpgo
    type: Opaque