# apps/sftpgo/resources/sealed-sftpgo-admin-secret.yaml.example
#
# Seal each key with:
#   printf '%s' 'admin' > /tmp/u && printf '%s' "$(openssl rand -base64 24)" > /tmp/p
#   kubeseal --raw --scope namespace-wide --namespace sftpgo --name sftpgo-admin-credentials --from-file=/tmp/u
#   kubeseal --raw --scope namespace-wide --namespace sftpgo --name sftpgo-admin-credentials --from-file=/tmp/p
#   rm /tmp/u /tmp/p
#
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sftpgo-admin-credentials
  namespace: sftpgo
spec:
  encryptedData:
    SFTPGO_DEFAULT_ADMIN_USERNAME: AgCmzpApHKoMDajt2xyS5/txhH917YGjFDVJcIx/nhfyHsY8mgbsuHkFqmNnJF2VidjRBHU0TPOiohx/qgg6aol8rxKHomtBWYqqkmwGajOzqe5HLEUq9jppa3ztvmD3ylXrE36abjsAYuiy3EJk6zXMQSjNGQLhUdooSr/tXM8dt5gF/SM7lyfhBAZs1G9+eRsZ0qZK/hex5xphF0HlxTnS9VJagylkp21sE//gt/GGjkQBChWCb0ZoeKGVH3AV7lqkGoxwZt/hnBCgfBif6BnePrpbOG9tH9x9X4dXl6sCrusVw62bybkyjRvT2DMPwr6YK8xv9XDIdW1yFYIogjKb9FxWufsnIfrHFRxcP1uN7MKO6sGztl66r/yZBrKK1TLnUFM2MI8/nBmXvkGqIcSoZWalPyHn2h/5RjC9v5x7wUFY3+yhCcECSo2GA0N/RhUGj+nnp4MBG4AwfZBXaot1oxWbaXMvX87SctR6SUgXhrViA5YJf2CPN2UsOOrnsr9LQymXlWOkrWsYzMzHzXSmJmJkaJ3RQXQ9BYQUHlIjTikAVktnyGzfXRl7vi8sCk3HMkQjdNCd/ge+wuO9WeMDATrRW4GbomYFLRxHPDepcs0xd4Dc1jQj4LPbEGCkmO/2PnefabAb2eUaNAAIulro2dDX9zxfmGxVLSUO2UzjUSCXWH88ZUSlU6KpenTfY2QYKBkKJbnm0IMKc9Mh1vMBYTgXtjTM/3aNGAFoLdkB5pU=
    SFTPGO_DEFAULT_ADMIN_PASSWORD: AgClQZhcFNzmd71w4fKJhzBP3dxuWQnPuxJsmFe3sLoS+YsrWVJLH/3dGxZ3way4cPqIlLX2AcNyGh2a6tyX38npKnz58ySWiUoLfRe4DLMIwfRQgzzFyeC/Z6E3jyRf7rBngcdDXYTsyGZr/YVR0xISYjdsl6gIv4iZ7Lj95sfhtSXwp+YbauHcRx4Vqaq2ZGW8wBOnbrqyBcjsNsdUxdU5u9v840WQGBXbL02UtKJU6KeDKLoK+zVCWBpXqTONB0LAxwAOEXmAbTA3AGWumiIsBfn1I6oLY27+5HwNvq3RU9uzbsz1brSSNMFtyPZGpofwETE950z4Egp4Pva67m+JXh31G59Dw+r50HiIrotnFSAZJ7FWFmZjoVBwv/jvZ640DmezT8VhFXCWm5I00S1+JJehDA9WlEuHnK9KXdX8pnLyLapbDtI9GuA5l1tA85Cccurx8fVw1bLvnP56nwmLy0fg/jrCdK+8pXufrfMWqZ/t2dykByUf7Nfs8TEyDIrK7X4LDuJ3434Gc3WglfVSzmR3hPmmduCVAj7aWyheMThZ9XgFBpzpnt9HUn8F648gonm19/QOjEGvbnJIneMvN+dE4cGXKs7a4FcEhHgWMHprpxJ8wsRzv2zsT2BdnuVUH/x/FzAiKIreCnbjipl9AX5gBC1x8FSll+rxBhUO5jTMbCAMDquQ43c3MabPFi47Zyewew==
  template:
    metadata:
      name: sftpgo-admin-credentials
      namespace: sftpgo
    type: Opaque