# infrastructure/authentik/postgresql/secret.yaml.example
#
# Generate a strong password:
#   openssl rand -base64 32 | tr -d '\n'
#
# Seal it:
#   kubeseal --format=yaml --controller-namespace kube-system \
#     < infrastructure/authentik/postgresql/secret.yaml.example \
#     > infrastructure/authentik/postgresql/sealed-secret.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: authentik-postgresql-credentials
  namespace: authentik
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgCCwhH9EcIUgPZpfux3zzaGm3pH4NwLAFTzEQPmTDMEZ2SFb0c6hg7OkrBcmOIcdMKmD/VRbCCZMoRGyGA5VR5LdU4hKBGmJz55PzVoIdKEeCGvfvE70EfbzZsKJjk7cBYI8OZMuFDoqt3ZsKOLZT2YZxxhFcr76YLKJJq2jp1SKGIneQqm0m9nw1IcNymhT4tKdPnOIFyZuvmnwCkAcvmraYe0qFK+v/ac11OAtlzjLFoPnzQVA+/8Dw5PqIlHnObI2+gUpOwmpb1v60vyGqSGIDx2Lal0mWnLnkviTZcxxQALCOVYKf+dW8rpQlvlL/h5TSN9jbQeOw8BfFDgkwnfgOJZYdO+UJUbcEIUb7ngsmtEW8meP6cCLw83fBZSKVHgvMa7fiK7qGvx1tO3+ZlBxtMrqXeJihfYccII3PBcCKdf5nmyd56pk/9oZ1ufHi53OkWCBbSUejIrXnKnJnQsjv8UpDlCfaVYN+Ou7jZhY7kUL1UqQpznhhNGvRYPEqXVO7ibshPK+CObEerVJYu57qwT/9khqgU73hDWjZDu24fSLVOw//tD/iU1ey0m0eRi7GMhoVLOmrzEpwoZ7ucJBt1tV50b4CAdlDKEXHEDL3DeeR0vJ3gZOl1LgYhuxoO9+QDtl0hWJsVps/Xjow+0YKT4bAhWm8kQPsIkNJxXacmz9QLPgfGwIwinAeqjHpHiWgp9HvteSqWp7LpAq2l1BoTYQxsl7NCsMPfnbJAVyOHovNiKt9gGLShJGg==
  template:
    metadata:
      name: authentik-postgresql-credentials
      namespace: authentik
    type: Opaque