# infrastructure/authentik/redis/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: authentik-redis
  namespace: authentik
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: authentik
spec:
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: authentik
  ports:
    - name: redis
      port: 6379
      targetPort: 6379