# k3s-gitops/infrastructure/cert-manager/namespace.yaml
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: cert-manager
