# apps/home-assistant/kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pvc.yaml
  - init-config.yaml
  - deployment.yaml
  - service.yaml
  - ingress-route.yaml
  - volsync-replication-source.yaml