# infrastructure/nfs-ganesha/namespace.yaml
# ---
apiVersion: v1
kind: Namespace
metadata:
  name: nfs-ganesha
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    app.kubernetes.io/name: nfs-ganesha