apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-paperless-smb-printerscans
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
    argocd.argoproj.io/sync-wave: "0"
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "" # static - never matched by a dynamic StorageClass
  mountOptions:
    - dir_mode=0770
    - file_mode=0660
    - uid=1000
    - gid=1000
    - vers=3.0
  csi:
    driver: smb.csi.k8s.io
    readOnly: false
    # format: {smb-server-address}#{sub-dir-name}#{share-name} - must be
    # unique across the cluster
    volumeHandle: 192.168.7.206#printerscans
    volumeAttributes:
      source: //192.168.7.206/printerscans
    nodeStageSecretRef:
      name: paperless-samba-creds
      namespace: paperless
